services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    expose:
      - "4000"
      - "9229"
    ports:
      - "4000:4000"
      - "9229:9229"
    command: npm run dev
